apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-latency-api.fullname" . }}
  labels:
    {{- include "payment-latency-api.labels" . | nindent 4 }}
data:
  REGION: {{ .Values.config.region | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
